### ISSUE TITLE
Mobie: design mismatch

### ISSUE THREAD

**Issue by eko24ive** [bogdanlotuk/Task6#1]
Below you can see screenshot of your website launched via DevTools emulator (IPhone 6 Plus).
Consider using value for mobile media query about ~`450px` because `768px` is too big for mobile - it used for tablet media rules.
![image](https://cloud.githubusercontent.com/assets/25591824/23178255/6a6c1d7c-f872-11e6-8c92-238fa41198af.png)

**Comment by bogdanlotuk** [comment]
Check please!!!!

**Comment by eko24ive** [comment]
Nicely done !

**Comment by eko24ive** [comment]
But it seems you forgot to remove green border for `.article_left`:
![image](https://cloud.githubusercontent.com/assets/25591824/23508650/6404d79a-ff5b-11e6-975a-25b2bf7d1b7b.png)

Please remove it
